Data preprocessing

In [2]:
import numpy as np
# for arrays
import matplotlib.pyplot as plt
# plotting the data 
import pandas as pd
# for data reading and changing that 

In [3]:
dataset=pd.read_csv('Data.csv')
print(dataset)
# feateurs= independent variable 
# ie country age salary
X=dataset.iloc[:,:-1].values
X
# ![row:column]
# dependent variable
# purchased
y=dataset.iloc[:,-1].values
y

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [4]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of the missing values

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(X[:,1:3])
#! selecting specifc columns as it will be used only for the missing values
#? add all numerical columns
X[:,1:3]=imputer.transform(X[:,1:3])
# only returns the changes in the df
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding Categorical Data

Encoding The Independent Variable

In [6]:
#!we can make a categy for country so there is no numerical column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#! used to encode data so there is no numerical pattern in the data
#* taking out the column transfer and one hot encoding 
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
# print("hi")
#! encoder , encoder name , colum in  brackets
X = np.array(ct.fit_transform(X))
#* returns changed value 
#! does not return as a numpy array
X




array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [7]:
# france 0 0 1
# germany 010
# spain 100


Encoding the Dependent Variable

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

Splitting the Dataset into the Training and Test Set

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1, test_size=0.2)
#! (X,Y,test_size(in percentage like 0.2 is 20%),randon_state=controls how data is shuffled , shuffle by default true to shuffle the data before spliting)
                                    

In [10]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [11]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [12]:
print(y_test)

[0 1]


In [13]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

Feature Scaling

In [14]:
#? to make sure some features are not affected by other features
# ! standardization all the time 
# ! normalization at some specific time
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
# todo do not aplly on standardization on duummy variables
# print(X_train[:,3:])
X_train[:,3:]=sc.fit_transform(X_train[:,3:])

In [15]:
# transform the X_test
# X_test[:,3:]=sc.fit_transform(X_test[:,3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])



In [16]:
X_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [17]:
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)